# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-cartographer
  version: 2.0.0

build:
  number: 13
  script: ''
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - git
  host:
    - cairo
    - ceres-solver
    - eigen
    - gflags
    - glog
    - gmock
    - gtest
    - libabseil
    - libboost-devel
    - libprotobuf
    - lua
    - protobuf
    - python
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
    - sphinx
    - if: build_platform == target_platform
      then:
        - git
  run:
    - cairo
    - cartographer >=2.0.0, <2.1.0a0
    - ceres-solver
    - eigen
    - gflags
    - glog
    - libabseil
    - libboost-devel
    - libprotobuf
    - lua
    - protobuf
    - python
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
