# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-ur-controllers
  version: 2.8.1
source:
  git: https://github.com/ros2-gbp/Universal_Robots_ROS2_Driver-release.git
  tag: release/humble/ur_controllers/2.8.1-1
  target_directory: ros-humble-ur-controllers/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-action-msgs
    - ros-humble-ament-cmake
    - ros-humble-angles
    - ros-humble-control-msgs
    - ros-humble-controller-interface
    - ros-humble-controller-manager
    - ros-humble-generate-parameter-library
    - ros-humble-geometry-msgs
    - ros-humble-hardware-interface
    - ros-humble-hardware-interface-testing
    - ros-humble-joint-trajectory-controller
    - ros-humble-lifecycle-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rcutils
    - ros-humble-realtime-tools
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2-control-test-assets
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-trajectory-msgs
    - ros-humble-ur-dashboard-msgs
    - ros-humble-ur-msgs
    - ros2-distro-mutex 0.7.* humble_*
  run:
    - python
    - ros-humble-action-msgs
    - ros-humble-angles
    - ros-humble-control-msgs
    - ros-humble-controller-interface
    - ros-humble-generate-parameter-library
    - ros-humble-geometry-msgs
    - ros-humble-hardware-interface
    - ros-humble-joint-trajectory-controller
    - ros-humble-lifecycle-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp-lifecycle
    - ros-humble-rcutils
    - ros-humble-realtime-tools
    - ros-humble-ros-workspace
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-trajectory-msgs
    - ros-humble-ur-dashboard-msgs
    - ros-humble-ur-msgs
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
