# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-rqt-common-plugins
  version: 1.2.0
source:
  git: https://github.com/ros2-gbp/rqt_common_plugins-release.git
  tag: release/humble/rqt_common_plugins/1.2.0-1
  target_directory: ros-humble-rqt-common-plugins/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-rqt-action
    - ros-humble-rqt-bag
    - ros-humble-rqt-bag-plugins
    - ros-humble-rqt-console
    - ros-humble-rqt-graph
    - ros-humble-rqt-image-view
    - ros-humble-rqt-msg
    - ros-humble-rqt-plot
    - ros-humble-rqt-publisher
    - ros-humble-rqt-py-common
    - ros-humble-rqt-py-console
    - ros-humble-rqt-reconfigure
    - ros-humble-rqt-service-caller
    - ros-humble-rqt-shell
    - ros-humble-rqt-srv
    - ros-humble-rqt-topic
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
