# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-image-proc
  version: 3.0.8
source:
  git: https://github.com/ros2-gbp/image_pipeline-release.git
  tag: release/humble/image_proc/3.0.8-1
  target_directory: ros-humble-image-proc/src/work
  patches:
    - patch/ros-humble-image-proc.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libopencv
    - numpy
    - pip
    - py-opencv
    - python
    - ros-humble-ament-cmake-auto
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-cv-bridge
    - ros-humble-image-geometry
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-rcutils
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-tracetools-image-pipeline
    - ros2-distro-mutex 0.7.* humble_*
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - libopencv
    - py-opencv
    - python
    - ros-humble-cv-bridge
    - ros-humble-image-geometry
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-rclcpp-components
    - ros-humble-rcutils
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-tracetools-image-pipeline
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
