# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-gtsam
  version: 4.2.0

build:
  number: 13
  script: ''
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build: []
  host:
    - eigen
    - libboost-devel
    - libboost-python-devel
    - python
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
    - tbb
    - tbb-devel
  run:
    - eigen
    - gtsam >=4.2.0, <4.3.0a0
    - libboost-devel
    - libboost-python-devel
    - python
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
    - tbb
    - tbb-devel
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
