# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-webots-ros2-tests
  version: 2025.0.0
source:
  git: https://github.com/ros2-gbp/webots_ros2-release.git
  tag: release/humble/webots_ros2_tests/2025.0.0-2
  target_directory: ros-humble-webots-ros2-tests/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-humble-ament-copyright
    - ros-humble-geometry-msgs
    - ros-humble-launch
    - ros-humble-launch-testing
    - ros-humble-launch-testing-ament-cmake
    - ros-humble-launch-testing-ros
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2bag
    - ros-humble-rosbag2-storage-default-plugins
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2-ros
    - ros-humble-webots-ros2-driver
    - ros-humble-webots-ros2-epuck
    - ros-humble-webots-ros2-husarion
    - ros-humble-webots-ros2-mavic
    - ros-humble-webots-ros2-tesla
    - ros-humble-webots-ros2-tiago
    - ros-humble-webots-ros2-turtlebot
    - ros-humble-webots-ros2-universal-robot
    - ros2-distro-mutex 0.7.* humble_*
    - setuptools
  run:
    - python
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
