# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-grid-map-demos
  version: 2.0.1
source:
  git: https://github.com/ros2-gbp/grid_map-release.git
  tag: release/humble/grid_map_demos/2.0.1-1
  target_directory: ros-humble-grid-map-demos/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-cv-bridge
    - ros-humble-geometry-msgs
    - ros-humble-grid-map-cmake-helpers
    - ros-humble-grid-map-core
    - ros-humble-grid-map-cv
    - ros-humble-grid-map-filters
    - ros-humble-grid-map-loader
    - ros-humble-grid-map-msgs
    - ros-humble-grid-map-octomap
    - ros-humble-grid-map-ros
    - ros-humble-grid-map-rviz-plugin
    - ros-humble-grid-map-visualization
    - ros-humble-octomap-msgs
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.7.* humble_*
  run:
    - libopencv
    - py-opencv
    - python
    - ros-humble-cv-bridge
    - ros-humble-geometry-msgs
    - ros-humble-grid-map-core
    - ros-humble-grid-map-cv
    - ros-humble-grid-map-filters
    - ros-humble-grid-map-loader
    - ros-humble-grid-map-msgs
    - ros-humble-grid-map-octomap
    - ros-humble-grid-map-ros
    - ros-humble-grid-map-rviz-plugin
    - ros-humble-grid-map-visualization
    - ros-humble-octomap-msgs
    - ros-humble-octomap-rviz-plugins
    - ros-humble-octomap-server
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-rviz2
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
