# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-microstrain-inertial-driver
  version: 4.7.0
source:
  git: https://github.com/ros2-gbp/microstrain_inertial-release.git
  tag: release/humble/microstrain_inertial_driver/4.7.0-1
  target_directory: ros-humble-microstrain-inertial-driver/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-humble-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - geographiclib-cpp
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-target-dependencies
    - ros-humble-ament-cpplint
    - ros-humble-diagnostic-updater
    - ros-humble-geometry-msgs
    - ros-humble-lifecycle-msgs
    - ros-humble-microstrain-inertial-msgs
    - ros-humble-nav-msgs
    - ros-humble-nmea-msgs
    - ros-humble-rclcpp-lifecycle
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-rtcm-msgs
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.7.* humble_*
  run:
    - python
    - ros-humble-diagnostic-aggregator
    - ros-humble-diagnostic-updater
    - ros-humble-geometry-msgs
    - ros-humble-lifecycle-msgs
    - ros-humble-microstrain-inertial-msgs
    - ros-humble-nav-msgs
    - ros-humble-nmea-msgs
    - ros-humble-rclcpp-lifecycle
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-rtcm-msgs
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros-humble-std-srvs
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
