# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-nav2-rviz-plugins
  version: 1.1.18
source:
  git: https://github.com/SteveMacenski/navigation2-release.git
  tag: release/humble/nav2_rviz_plugins/1.1.18-1
  target_directory: ros-humble-nav2-rviz-plugins/src/work
  patches:
    - patch/ros-humble-nav2-rviz-plugins.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 13
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - qt-main
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-geometry-msgs
    - ros-humble-nav-msgs
    - ros-humble-nav2-lifecycle-manager
    - ros-humble-nav2-msgs
    - ros-humble-nav2-util
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-resource-retriever
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rviz-common
    - ros-humble-rviz-default-plugins
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.7.* humble_*
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - python
    - qt-main
    - ros-humble-geometry-msgs
    - ros-humble-nav-msgs
    - ros-humble-nav2-lifecycle-manager
    - ros-humble-nav2-msgs
    - ros-humble-nav2-util
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclcpp-lifecycle
    - ros-humble-resource-retriever
    - ros-humble-ros-workspace
    - ros-humble-rviz-common
    - ros-humble-rviz-default-plugins
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-std-msgs
    - ros-humble-tf2-geometry-msgs
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
