jobs:
  stage_0_job_0:
    name: rosbag2-storage-mcap-testdata mcap-vendor pid-controller rosx-introspection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosbag2-storage-mcap-testdata ros-humble-mcap-vendor
        ros-humble-pid-controller ros-humble-rosx-introspection
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosbag2-storage-mcap-testdata ros-humble-mcap-vendor
          ros-humble-pid-controller ros-humble-rosx-introspection
        DOCKER_IMAGE: condaforge/linux-anvil-cos7-x86_64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
  stage_1_job_1:
    name: rosbag2-storage-mcap
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosbag2-storage-mcap
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosbag2-storage-mcap
        DOCKER_IMAGE: condaforge/linux-anvil-cos7-x86_64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
name: build_linux
on:
  push:
    branches:
    - buildbranch_linux
